# import polars as pl
# (pl.scan_csv("log_files_cleaned.tsv", separator="\t")
#    .filter(pl.col("query").is_not_null() & (pl.col("query") != ""))
#    .filter(pl.col("serp").is_not_null()  & (pl.col("serp")  != ""))
#    .with_columns(pl.col("date").cast(pl.Int64, strict=False).alias("ts"))
#    .filter(pl.col("ts").is_not_null())
#    .select(["ts", "query", "serp", "search_id"])
#    .sort("ts").head(2_000_000)
#    .sink_csv("dis22_sorted.tsv", separator="\t"))
# print("Stage 1 fertig -> dis22_sorted.tsv")
import polars as pl
(pl.scan_csv("../../data/log_files_cleaned.tsv", separator="\t")
   .filter(pl.col("query").is_not_null() & (pl.col("query") != ""))
   .filter(pl.col("serp").is_not_null()  & (pl.col("serp")  != ""))
   .with_columns(pl.col("date").cast(pl.Int64, strict=False).alias("ts"))
   .filter(pl.col("ts").is_not_null())
   .select(["ts", "query", "serp", "search_id", "trackId", "type", "uid"])  # alle Spalten
   .sort("ts")
   .sink_csv("../../data/dis22_sorted.tsv", separator="\t"))
print("Stage 1 fertig -> ../../data/dis22_sorted.tsv (mit allen Spalten)")